name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Features'
    labels:
      - 'enhancement'
      - 'feature'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: 'Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: 'Refactoring'
    labels:
      - 'refactor'
  - title: 'Performance'
    labels:
      - 'performance'
  - title: 'Tests'
    labels:
      - 'test'
      - 'tests'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'enhancement'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'fix'

template: |
  ## Changes

  $CHANGES
